### ISSUE TITLE
Can we have compressed image from plugin itself(by providing quality percentages as parameter) ?

### ISSUE THREAD

**Issue by jdixosnd** [BlinkID/blinkid-phonegap#100]
I have to compress the size of the image that I receive from BlinkID plugin(scanned image, raw image, and photograph). Does blinkid provide this feature?

**Comment by juraskrlec** [comment]
Hi @jdixosnd 

So, you want to resize images? There is no option now to resize image from BlinkID plugin. We can see what we can do about that.

Best regards,
Jura

**Comment by jdixosnd** [comment]
Thanks @juraskrlec !
