### ISSUE TITLE
Multiple settings objects of type <selected card recognizer> found. This is not supported!

### ISSUE THREAD

**Issue by jdixosnd** [BlinkID/blinkid-phonegap#103]
I have updated my blinkid-cordova version from v4.7.0 to v4.8.0. After update I am trying to run the plugin but it gives following error.

Multiple settings objects of type 'Malaysian MyKad front side recognizer' found. This is not supported!

`Failed to initialize BlinkID
ERROR_STATUS_DUPLICATE_ENTRY: duplicate entry found where disallowed
NativeRecognizerWrapper.java:154@Recognition: Failed to initialize native library!
NativeRecognizerWrapper.java:155@Recognition: Reason:    ERROR_STATUS_DUPLICATE_ENTRY: duplicate entry found where disallowed
libc: Access denied finding property "camera.hal1.packagelist"`

I am not sure what it means by default entry. Please help me to resolve this issue.

**Comment by i1E** [comment]
Hi @jdixosnd,

it seems that you have added two instances `Malaysian MyKad front side recognizer` to the [recognizer collection](https://github.com/BlinkID/blinkid-phonegap/blob/master/www/js/index.js#L81), and that is not allowed.

**Comment by jdixosnd** [comment]
Thank you @i1E !!
