### ISSUE TITLE
Upgraded cordova to 9.0.0, can't compile BlinkID

### ISSUE THREAD

**Issue by AlibekJ** [BlinkID/blinkid-phonegap#104]
Compilation fails with:

`Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

Got away by commenting out everything in `/plugins/blinkid-cordova/scripts/fix-largeheap.js`

This line seems to be causing issues:
`var fs = ctx.requireCordovaModule('fs')`

**Comment by i1E** [comment]
Hi @AlibekJ, 
latest version of the BlinkID plugin (v4.8.0) should work, we commented line that includes fix-largeheap.js in [plugin.xml](https://github.com/BlinkID/blinkid-phonegap/blob/master/BlinkID/plugin.xml#L171).
