### ISSUE TITLE
Changing MicroBlink logo Android

### ISSUE THREAD

**Issue by nsdonev** [BlinkID/blinkid-phonegap#11]
Is there any way to remove or change Microblink logo that is appearing on sdk intialization ?
I tried to add `intent.putExtra(ScanCard.EXTRAS_SPLASH_SCREEN_LAYOUT_RESOURCE, fakeR.getId("raw", "test"));` directly in BlinkIdScanner.java file located in generated plugins directory, but no luck at all.
Thanks !

**Comment by i1E** [comment]
Hi @nsdonev,

to achieve that, you have to modify the phonegap plugin. You should update BlinkIdScanner.java as you did but instead of `intent.putExtra(ScanCard.EXTRAS_SPLASH_SCREEN_LAYOUT_RESOURCE, fakeR.getId("raw", "test"));` you should add this line of code:

```
intent.putExtra(ScanCard.EXTRAS_SPLASH_SCREEN_LAYOUT_RESOURCE, fakeR.getId("layout", "test"));
```

This assumes that there exists `test.xml` layout resource file in the `res/layout` folder of the deployed app. To copy your custom layout for splash screen, create `blinkid-phonegap/BlinkID/src/android/res/layout` folder and put your `test.xml` layout file inside.

Next step is modifying the [plugin.xml](https://github.com/BlinkID/blinkid-phonegap/blob/master/BlinkID/plugin.xml) file. You should declare new source file that will be copied, after [this](https://github.com/BlinkID/blinkid-phonegap/blob/master/BlinkID/plugin.xml#L60) line add the following one:

```
<source-file src="src/android/res/layout/test.xml" target-dir="res/layout" />
```

Run `initCordovaDemoApp.sh` or `initIonicDemoApp.sh` script again and splash screen should be updated.

Best regards

**Comment by nsdonev** [comment]
Hello @i1E,

Thank you for the fast response! Could you please provide me an example of test.xml content ?
Also is this possible in IOS , i am building ionic hybrid app and i am not really experienced both in Java and Swift.
Thank you

**Comment by Cerovec** [comment]
Hi,
where exactly does this happen on iOS?
Can you post a screenshot which shows this?
Thanks,
Jurica.

**Comment by i1E** [comment]
Hi @nsdonev,

here is an example for `test.xml` content:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@android:color/white"
                tools:ignore="Overdraw">

    <ImageView
        android:id="@+id/imageView1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:src="@drawable/logo"
        android:background="@color/transparent"
        tools:ignore="ContentDescription"/>

    <TextView
        android:id="@+id/textView1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/imageView1"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="18dp"
        android:text="@string/loading"
        android:textColor="#FF000000"
        android:textSize="24sp"
        android:background="@color/transparent"
        tools:ignore="UnusedIds"/>

</RelativeLayout>
```

If you reference your own drawable resource (or some other resource file) in this layout file, you have to declare it in the [plugin.xml](https://github.com/BlinkID/blinkid-phonegap/blob/master/BlinkID/plugin.xml) file, like you did for `test.xml`.

**Comment by talamaska** [comment]
Also maybe it will be great to know how to control the splash screen on iOS as well. 
I would like to add more questions to this thread, as they are related to the splash. I have a requirement to make the splashscreen go away faster, how can I change this?

**Comment by Cerovec** [comment]
Hi,
a couple of questions:
1) can you explain what do you mean by splash screen on iOS? We don't have it on iOS.
2) the splash screen duration on Android is related to the time it takes to open the camera. It cannot be open faster - it's related to the hardware.

If you believe you have some issue and that it can be opened faster, please attach a video which shows the current state of your app.

**Comment by talamaska** [comment]
1. my bad
2. thanks

**Comment by nsdonev** [comment]
Is there any way to just remove it  ?

**Comment by i1E** [comment]
Hi @nsdonev,

yes, you can remove splash screen by creating layout resource which is completely transparent. That layou resource you should pass through intent extras to scan activity as I have described in [previous response](https://github.com/BlinkID/blinkid-phonegap/issues/11#issuecomment-279975738).

**Comment by talamaska** [comment]
@Cerovec, there is a white screen with logo of microblink before the camera is started. It appears on ios and on Android. This is what we call splash screen.

**Comment by talamaska** [comment]
[Untitled.zip](https://github.com/BlinkID/blinkid-phonegap/files/952244/Untitled.zip)
here is a demo of the splash screen on android

**Comment by Cerovec** [comment]
Hi Talamaska,

On Android, this screen can be removed by the code Ivan shared with you.
> You can remove splash screen by creating layout resource which is completely transparent. That layou resource you should pass through intent extras to scan activity as I have described in previous response.  

Did you try this approach? If yes, where did you experience problems?

On iOS, if you're referring to the screen attached, this screen is part of the demo app, and not a part of the SDK. Once you add the plugin to your app, you won't see this screen.

If you're referringto some other screen, please attach an image.

Best,
Jurica.

![simulator screen shot 24 apr 2017 17 28 10](https://cloud.githubusercontent.com/assets/628039/25344761/67bc6d94-2913-11e7-8251-b02c7a01c685.png)

**Comment by i1E** [comment]
Hi @nsdonev, @talamaska,

the Android splash screen is removed now, you should just update to the latest version of the plugin.

**Comment by nsdonev** [comment]
Hi @i1E . I downloaded zip with the latest change. Also deleted plugin folder just to be sure when i build, it will be with the latest code. However there is no change and the logo is still there. I checked every line that you added in all changed files and everything matches. Am i missing something else obvious ?

**Comment by DoDoENT** [comment]
Hi @nsdonev! Please make sure that you are using the [latest master branch](https://github.com/BlinkID/blinkid-phonegap/commit/22916ee405e709c6a6079db134c5a78dadc28b7c). Also make sure that you have re-inited your cordova app after updating the plugin.

If the splash screen still appears, please record and send us a short video which shows how splash screen is being displayed.

**Comment by nsdonev** [comment]
I can confirm, after cloning the repo and updating its submodules with latest code splash dissapeared.
Thanks for all your help 👍

**Comment by Cerovec** [comment]
If your issue has been resolved, please close it.
@talamaska - if the splash screen can be reproduced on iOS - you can open another issue specifically for this.
