### ISSUE TITLE
Scan front of the ID without MRZ

### ISSUE THREAD

**Issue by nsdonev** [BlinkID/blinkid-phonegap#14]
Hello,

Is there any way to trigger scan on the front of  US ID. 
I dont need data from it, only the cropped image object.
I see that MRTD works perfectly fine with EU ID cards but i cant seem to find option for US Cards.
Is it a limitation on the phonegap wrapper, because from what i understand from the overview in the website there is a way to scan ID with or without MRZ (Machine-Readable Zone) or barcode.

Thanks !

**Comment by jcular** [comment]
Closed because this is no longer relevant to the current SDK version we support, if the problem persist in the newer version, please open a new issue.
