### ISSUE TITLE
"beep.mp3" not found

### ISSUE THREAD

**Issue by hollyx** [BlinkID/blinkid-phonegap#2]
Hi great library, thanks for your work.
When running 

`cordova platform add android`

I'm getting the error

`Error: Uh oh!
"<my-project-path>/testcordova/plugins/com.microblink.BlinkIdScanner/src/android/blinkid-android/beep.mp3" not found!`

**Comment by DoDoENT** [comment]
Have you initialized and updated submodules as described in [README](https://github.com/BlinkID/blinkid-phonegap#submodules)?

**Comment by errolgr** [comment]
I had the same problem. I manually added beep.mp3 to the project.

**Comment by DoDoENT** [comment]
@errolgr, that hack probably made your project compile, but will most probably crash when deployed on phone because key java classes, native libraries and resources (which are in submodule) are missing.

**Comment by errolgr** [comment]
Yes I forgot to include that aswell. I copied over the android module. However I did some directory cleanup as there was useless files that were not being used.Date: Wed, 7 Sep 2016 12:19:42 -0700
