### ISSUE TITLE
Error: Recognizer type not supported: DocumentFace

### ISSUE THREAD

**Issue by rachitaroraa** [BlinkID/blinkid-phonegap#20]
According to the sample present in www, I am adding DocumentFace as types

/**
         * Use these scanner types
         * Available: "PDF417", "USDL", "Barcode", "MRTD", "EUDL", "UKDL", "DEDL", "MyKad", "DocumentFace"
         */
        var types = ["PDF417", "UKDL", "MRTD", "Barcode","DocumentFace"];

this is opening a dialog box with Error: Recognizer type not supported: DocumentFace.

I am new to Blink Id and also not able to find proper document regarding this.
I wanted to scan the passport and also need the image from it.
Please suggest.

**Comment by lirfu** [comment]
Hi @rachitaroraa,

thank you for reporting this issue. The new release (1.1.8) fixes this issue.

The code sample for configuration of various recognizers and result extraction for Android can be found [here](https://github.com/BlinkID/blinkid-phonegap/blob/feature/android-addDocumentFaceRecognizer/BlinkID/src/android/java/com/phonegap/plugins/blinkid/BlinkIdScanner.java).

The code sample for using the result image is [here](https://github.com/BlinkID/blinkid-phonegap/blob/feature/android-addDocumentFaceRecognizer/www/js/index.js) on lines 95-100.

Detailed documentation for the BlinkId SDK for Android is [here](https://github.com/BlinkID/blinkid-android).

If you're satisfied with this answer please close this issue. Thank you!

**Comment by lirfu** [comment]
Dear @rachitaroraa,

can you please verify that your issue is solved?
