### ISSUE TITLE
Submodules installation for Oracle MAF

### ISSUE THREAD

**Issue by saifkamaal** [BlinkID/blinkid-phonegap#22]
Hi,

thnks for the API. I am trying to use the Cordova api in Oracle MAF Mobile Application, however, i got the beep.mp3 error. I read the readme and it seems i need to have the submodules. Any points how to get and add those modules manually.

**Comment by lirfu** [comment]
Hi @saifkamaal,

before doing anything be sure you have installed the [required dependencies](https://github.com/BlinkID/blinkid-phonegap#dependencies).

Then follow the instructions described in the [README.md](https://github.com/BlinkID/blinkid-phonegap#submodules) and git will automatically download and add all the required submodules to your project.

[This file](https://github.com/BlinkID/blinkid-phonegap/blob/master/.gitmodules) contains all the required submodules and their git repositories.

Hope this solves your problem, if it does be sure to close this issue.
Thanks!

**Comment by saifkamaal** [comment]
thanks.. I added the sub module and was able to build the android application.
