### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by kiranAndr** [BlinkID/blinkid-phonegap#24]
Getting **Uncaught TypeError: Cannot read property 'blinkIdScanner' of undefined at HTMLButtonElement.<anonymous>**  error in index.js:79 line. Can you please check it once

**Comment by lirfu** [comment]
Hi @kiranlanke,

are you getting this error in our demo app or in your app?

Also, please check have you added the BlinkID plugin to your project since it defines `blinkIdScanner`.

**Comment by kiranlanke** [comment]
Hi lirfu,
Thank you for your valuable response. I'll try it and let you know...

**Comment by lirfu** [comment]
Hi @kiranAndr,

have you managed to solve this problem?

**Comment by jcular** [comment]
Closed due to inactivity.
