### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by kiranAndr** [BlinkID/blinkid-phonegap#25]
Hi,

I'm trying to clone the project for android as listed below

                              - mkdir DEMO
                              - cd DEMO
                              - git clone https://github.com/BlinkID/blinkid-phonegap.git
                              - cd blinkid-phonegap
                              - git submodule init
                              - git submodule update

but when executing the `git submodule update`  i'm getting the error like **Host key verification failed. fetal: Could not read from remote repository**

For other details please refer the attached screenshot 

![capture](https://user-images.githubusercontent.com/15002093/29809042-2f9015f2-8cb8-11e7-9a27-b9f8a6683403.PNG)

Can you please suggest me how to clone the project successfully

**Comment by lirfu** [comment]
Hi @kiranAndr,

you need to add your SSH key to your GitHub account in order to clone repositories with SSH (the blinkid-ios url is for SSH).

Alternatively, you can just edit [this file](https://github.com/BlinkID/blinkid-phonegap/blob/master/.gitmodules) by replacing the SSH url for iOS with HTTPS (`https://github.com/BlinkID/blinkid-ios.git`) and repeat the submodule initialization procedure.

Hope this solves your issue, if so please close this issue. Thanks!

**Comment by kiranAndr** [comment]
Hi @lirfu 

As you mentioned in the second fix i have edited the `.gitmodules` file as below

`[submodule "BlinkID/src/android/blinkid-android"]
	
path = BlinkID/src/android/blinkid-android
	url = https://github.com/BlinkID/blinkid-android.git	
[submodule "BlinkID/src/ios/blinkid-ios"]
	path = BlinkID/src/ios/blinkid-ios
	url = https://github.com/BlinkID/blinkid-ios.git`

after this i have executed`git submodule init` and `git submodule update` but i'm getting error like **Permission denied (publickey).
fatal: Could not read from remote repository.**

![capture](https://user-images.githubusercontent.com/15002093/29819271-90489386-8cdd-11e7-9618-55f94940d211.PNG)

**Comment by DoDoENT** [comment]
Hi @kiranAndr.

You need to correctly setup your github account and access keys, as explained in [github documentation](https://help.github.com/articles/error-permission-denied-publickey/).

**Comment by kiranAndr** [comment]
Hi @DoDoENT,

Thank you for your great suggestion it's worked for me...
