### ISSUE TITLE
Ionic build broken

### ISSUE THREAD

**Issue by emgould** [BlinkID/blinkid-phonegap#28]
the ionicDemo script does not generate an app.module.ts.  So it does not build.

**Comment by lirfu** [comment]
Hi @emgould,

the new release [v1.3.0](https://github.com/BlinkID/blinkid-phonegap/releases/tag/v1.3.0) adds support for Ionic v3 and it might resolve your issue.

Can you please confirm does this resolve your issue?

**Comment by jcular** [comment]
Closed due to inactivity.
