### ISSUE TITLE
Cannot add IOS platform to ionic app

### ISSUE THREAD

**Issue by veti-io** [BlinkID/blinkid-phonegap#29]
The `ionic cordova platform add ios` command cannot find **CDVblinkIdScanner.m**.
This happens when following the guidance of the documentation in the README. I used the init script to create a sample blank app, add the cordova plugin, then the android platform, and then the ios platform. On adding the ios platform I received the following error:
````
$ ionic cordova platform add ios
> cordova platform add ios --save
Using cordova-fetch for cordova-ios@~4.4.0

Adding ios project...

Creating Cordova project for the iOS platform:

	Path: platforms/ios
	Package: io.veti.alphaapp
	Name: AlphaApp
iOS project created with cordova-ios@4.4.0

Installing "com.microblink.BlinkIdScanner" for ios
Error during processing of action! Attempting to revert...

Failed to install 'com.microblink.BlinkIdScanner': Error
    at copyFile (/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/platforms/ios/cordova/lib/plugman/pluginHandlers.js:319:36)
    at copyNewFile (/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/platforms/ios/cordova/lib/plugman/pluginHandlers.js:351:5)
    at installHelper (/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
    at install (/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
    at ActionStack.process (/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/platforms/ios/cordova/Api.js:235:10)
    at handleInstall (/usr/local/opt/nvm/versions/node/v8.2.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:619:6)
    at /usr/local/opt/nvm/versions/node/v8.2.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:379:28
Error: Uh oh!
"/Users/kent/git/veti/cordova-plugins/blinkid-phonegap/AlphaApp/plugins/com.microblink.BlinkIdScanner/src/ios/sources/CDVblinkIdScanner.m" not found!
[ERROR] Exception:
````

After I manually added the files from **BlinkID/src/ios/sources** to my projects **plugins/com.microblink.BlinkIdScanner/src/ios/sources** directory then adding the ios platform worked. The **plugins/com.microblink.BlinkIdScanner/src/ios/sources** directory did not exist after I installed the plugin and I had to manually create it.

Will you fix this so that I can add the **ios** platform normally?

**Comment by veti-io** [comment]
There appear to be some problems in the CDVblinkIdScanner.m file

The import needs to have the B in upper case
````
#import "CDVBlinkIdScanner.h"
````

And XCode complains about scan1DCodes not being defined so I had to comment it out
````
    /**
     * Set this to YES if you want to scan 1D barcodes if they are present on the DL.
     * If NO, just PDF417 barcode will be scanned.
     */
    // usdlRecognizerSettings.scan1DCodes = NO;
````

Please resolve those as well.

**Comment by mladilav** [comment]
Any news?

**Comment by cularj** [comment]
Hi

what version of blinkID-phonegap are you using?
This looks like you are using an older version of blinkID-phonegap, but your blinkID SDK is updated to a new version.

Kind regards,
Jure

**Comment by mladilav** [comment]
@cularj  v 1.3.0

**Comment by mladilav** [comment]
@cularj I get Error: Uh oh!
"/PROJECT_PATH/plugins/com.microblink.BlinkIdScanner/src/ios/sources/CDVblinkIdScanner.m" not found!

**Comment by cularj** [comment]
Hi @mladilav,

what version of ionic are you using, are you also getting this error when you start the script `initIonicDemoApp` to create the demo app?

Kind regards,
Jure

**Comment by mladilav** [comment]
@cularj

**Comment by mladilav** [comment]
@cularj  Demo app start without errors, but when I press "Scan" nothing happens and the console is empty

**Comment by cularj** [comment]
@mladilav 

I am currently using the latest version of Ionic 3.16.0, try updating to that version and let us know if that works.

Kind regards,
Jure

**Comment by mladilav** [comment]
@cularj in DemoApp

 Installing "com.microblink.BlinkIdScanner" for ios
        Error during processing of action! Attempting to revert...
        Failed to install 'com.microblink.BlinkIdScanner':CordovaError: Uh oh!
        "/Users/olga/PhoneGapApp/blinkid-phonegap/BlinkIdDemo/plugins/com.microblink.BlinkIdScanner/src/ios/sources/CDVblinkIdScanner.m"
        not found!

**Comment by mladilav** [comment]
@cularj  You use Ionic 3.16.0, and I use 3.5.0. What you mean about "try updating" ?

**Comment by cularj** [comment]
@mladilav 

Uhm... latest version if 3.16.0 see [npm](https://www.npmjs.com/package/ionic) also [github](https://github.com/ionic-team/ionic-cli/releases). 

Still if that didn't resolve the problem, are you getting any errors while running `
ionic cordova plugin add <path to BlinkID directory>` in your app directory?
It could be an issue with git-lfs, do you have git-lfs installed?

Kind regards,
Jure

**Comment by cularj** [comment]
@mladilav 

Does your directory `BlinkID/src/ios/sources` contain `CDVblinkIdScanner.m` and `CDVblinkIdScanner.h` files?

Kind regards,
Jure

**Comment by mladilav** [comment]
@cularj 

After run sh script ./initIOSFramework.sh not, but I download them and added manually. On ios plugin does not work and there are no errors in the console.

**Comment by cularj** [comment]
The script clones the ios framework, not the wrapper files, they should be there when you cloned phonegap repo. If these files weren't there from the start maybe some other files are also missing, thus this error happens. Maybe try cloning it again?

Kind regards,
Jure

**Comment by mladilav** [comment]
@cularj 
I tried several times. Its not work. When I cloned repo, there were files, after run script they removed. I cloned repo again and copy files to my project manually. I do not know what files may be missing yet. But following your instructions in the readme plugin on ios does not work. Can you help me with that?

**Comment by cularj** [comment]
@mladilav 

Does running `git status` in blinkid-phonegap output anything?
It should be enough to run initIonicDemoApp script and it should setup the whole application, you can change the name of the id and the name of application in the script by changing APP_NAME and APP_ID variables.

Kind regards,
Jure

**Comment by mladilav** [comment]
@cularj I cloned repo https://github.com/BlinkID/blinkid-ios to BlinkID/src/ios/  and them in my project path run ionic cordova plugin add <path to BlinkID directory.This error is no longer present, but app not start with error

**Comment by cularj** [comment]
When you open your ios app, is Microblink.framework in embedded binaries, if it's not try adding it?

**Comment by mladilav** [comment]
@cularj  

it works! But https://drive.google.com/file/d/1kbITNa0GAIiW-Ly1NFb2kPOjdM7An8YT/view?usp=sharing headers are incorrect. How to fix it?

**Comment by cularj** [comment]
That means that the framework localisation doesn't support your device language, but you can force the framework to use english. We'll fix this in a future release, but for now you can use this workaround. Just add this line:`settings.uiSettings.language = @"en";` to CDVblinkIdScanner.m file after `PPSettings *settings = [[PPSettings alloc] init];`.

Kind regards,
Jure

**Comment by mladilav** [comment]
@cularj thanks!

**Comment by mladilav** [comment]
@cularj and where can I see a list of languages that are available?

**Comment by cularj** [comment]
@mladilav  

Currently only english is packed in the bundle, the file is `en.strings`. If you want you can add more languages by adding `.string` files in the bundle and matching keys from `en.strings` to the translation into the language you want. 

Kind regards,
Jure

**Comment by cularj** [comment]
I'll add steps for a workaround here, until next release, where fix will be provided
A problem is in our script that clones the ios framework:

- Clone bilnkid-phonegap repository or reset all changes in the current one
- Open initIOSFramework.sh in BlinkID directory and replace this line `git clone "git@github.com:BlinkID/blinkid-ios.git"` with this line `git clone https://github.com/BlinkID/blinkid-ios.git`
- Start initIonicDemoApp.sh script

**Comment by mladilav** [comment]
@cularj

**Comment by cularj** [comment]
Hi @mladilav,

currently no due to limitations of the wrapper, you could implement this setup through the wrapper. But this is not the intended usage of our frameworks localisation since by default, language that is used is the language of the device and it is determined automatically. If you wish to use only one language then you can set it how I mentioned before.

Could you describe your intended usage, would you do your own checks and determine what language to set, or would you just like to set the language to english for example but through js?

Kind regards,
Jure

**Comment by mladilav** [comment]
Hi @cularj,

We want to add all the languages we need, by the method you described earlier. And set language as a parameter.

For example,

cordova.plugins.blinkIdScanner.scan (callback (scanningResult), errorHandler (err), types, imageType, licenseiOs, licenseAndroid, **lang**);

**Comment by cularj** [comment]
@mladilav 

yes you can do that, but please note that `settings.uiSettings.language` property receives only one language. Check out how other parameters are set in our wrapper specifically `- (void)scan:(CDVInvokedUrlCommand *)command` method and `command` parameter, it shouldn't be to hard to implement as a workaround. We'll have to think about adding this feature to our wrapper.

Kind regards,
Jure

**Comment by mladilav** [comment]
@cularj

**Comment by cularj** [comment]
@mladilav 

sure, you can contact us and we'll send you the english version of all the UI texts in SDK. You can than provide the translation for all the languages you need and we'll add it to the SDK.

**Comment by jagan27101986** [comment]
Hi

I am using Cordova 7.0 , IOS 4.4.0 and it is throwing the same error. The version for blink is 1.4.0 Tag from the Repository. Please advise how to fix it.

**Comment by jcular** [comment]
Hi this has been solved in the newer plugin releases, if the problem persists please open a new issue.
