### ISSUE TITLE
Front side for ID Cards

### ISSUE THREAD

**Issue by mladilav** [BlinkID/blinkid-phonegap#33]
Hello!

Tell me please whether this plugin can scan the front side for ID cards?

**Comment by cularj** [comment]
Hi @mladilav 

yes it can but it depends what card you are trying to scan. Most ID's have MRTD on the back and it contains most if not all information from the card so there's usually no need to scan the front side, but as I said it depends on the type of ID. If you need to scan the front of the card to get the image or face you can use document face recogniser. 
What ID's are you trying to scan?

Kind regards,
Jure

**Comment by jcular** [comment]
Closed due to inactivity.
