### ISSUE TITLE
Backward Compatiblity

### ISSUE THREAD

**Issue by kashif-imagyn** [BlinkID/blinkid-phonegap#35]
I am Working On Ionic V3 Project which has many other plugins and most of them not supported  "cordova-android" version=">=7.0.0"
what should i do to use this plugin without upgrading

**Comment by DoDoENT** [comment]
You can use [this branch](https://github.com/BlinkID/blinkid-phonegap/tree/support/old-android-plugin) which supports cordova-android >= 4.0.0
