### ISSUE TITLE
SyntaxError: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "/" found.

### ISSUE THREAD

**Issue by premcarver** [BlinkID/blinkid-phonegap#37]
Uninstalling com.microblink.BlinkIdScanner from ios
(node:13673) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "/" found.

**Comment by cularj** [comment]
Hi @premcarver 

could you give us some more details, what version of Cordova you have, also what version of blinkid-phonegap are you using?

Kind regards,
Jure

**Comment by headdetect** [comment]
I kept getting this error when trying to build. I fixed it by deleting `node_modules`, `platforms`, and `plugins`. Then doing: 
```
npm i
ionic cordova prepare
```

Once I did that everything started building correctly again. (And I assume you can properly uninstall it too)

**Comment by premcarver** [comment]
@headdetect: Thanks a lot! It works for me :)
