### ISSUE TITLE
How to add IndonesianIDFrontRecognizerSettings?

### ISSUE THREAD

**Issue by huijing** [BlinkID/blinkid-phonegap#50]
According to the [blinkid-android documentation](https://github.com/BlinkID/blinkid-android#indonesianID_front), to add support for scanning Indonesian ID cards, there are 2 relevant code snippets:

```java
private RecognizerSettings[] setupSettingsArray() {
	IndonesianIDFrontRecognizerSettings sett = new IndonesianIDFrontRecognizerSettings();
	
	// now add sett to recognizer settings array that is used to configure
	// recognition
	return new RecognizerSettings[] { sett };
}
```
```java
@Override
public void onScanningDone(RecognitionResults results) {
	BaseRecognitionResult[] dataArray = results.getRecognitionResults();
	for(BaseRecognitionResult baseResult : dataArray) {
		if(baseResult instanceof IndonesianIDFrontRecognitionResult) {
			IndonesianIDFrontRecognitionResult result = (IndonesianIDFrontRecognitionResult) baseResult;
			
	        // you can use getters of IndonesianIDFrontRecognitionResult class to 
	        // obtain scanned information
	        if(result.isValid() && !result.isEmpty()) {
				String name = result.getName();
				String placeOfBirth = result.getPlaceOfBirth();
	        } else {
	        	// not all relevant data was scanned, ask user
	        	// to try again
	        }
		}
	}
}
```
Are we supposed to add them to the `BlinkIdScanner.java` file in `src`? Then what modifications are needed on the Javascript side to make it work?

**Comment by i1E** [comment]
Hi @huijing,

you can see all needed modifications from the commits that we made for adding the UAE ID support. Please check diff of [this merge commit](https://github.com/BlinkID/blinkid-phonegap/commit/949c79db13904ae1556272f0e9f10e15ab76fa2e).

**Comment by huijing** [comment]
Are you saying I don't need to make changes to the `BlinkIdScanner.java` file? And just modify the javascript files as per the commit you linked to? Where do I get the information required for the `uae_id_keys.js` but for Indonesian IDs?
Sorry, I'm still not very familiar with how BlinkID works yet.

**Comment by huijing** [comment]
So I also need to add something like:
```java
private JSONObject buildUaeIDBackResult(UnitedArabEmiratesIDBackRecognitionResult res) throws JSONException{
        JSONObject result = buildKeyValueResult(res, RecognizerType.UAE_ID_BACK.resultId);
        putDocumentImageToResultJson(result, UnitedArabEmiratesIDBackRecognitionResult.class);
        putFaceImageToResultJson(result, UnitedArabEmiratesIDBackRecognitionResult.class);
        return result;
    }
```
but for the `IndonesianIDFrontRecognitionResult.class`? I apologise but I've never done Java before so this is a bit tricky for me.

**Comment by i1E** [comment]
Hi @huijing,

we are planning to add support for the Indonesian ID in the next two weeks. If this is OK for you, and you can wait, you don't need to do it by yourself.

**Comment by huijing** [comment]
Okay, thank you for the update. I can close this issue now.
