### ISSUE TITLE
Not able to scan iKad cards

### ISSUE THREAD

**Issue by sipayyav** [BlinkID/blinkid-phonegap#51]
Hi,

I am not able to scan the Malaysian iKad cards. 

I defined typed as below.

 var types = ["IKad","USDL", "MRTD", "Barcode", "MyKad" ];

After running in device, getting error as follows "Error : Recognizer type not supported: IKad".

Kindly help me to resolve the issue.

**Comment by matvidako** [comment]
Hi,

please make sure you have the latest code.
Once you've pulled the latest code changes you'll also have to change "MyKad" to "MyKadFront".

**Comment by sipayyav** [comment]
Hi,

I am using android version 6.4.0 and the plugin version 1.5.1. 
Since I am working with MFP(Mobile first platform) I am not able to use the android 7 version , as MFP plugins are not supporting for android 7 version.

I changed cordova-android version in plugin.xml and package.json as below for the latest version of plugin.
```

<engines>
        <engine name="cordova" version=">=3.0.0" />
        <engine name="cordova-android" version=">=4.0.0" />
    </engines>  
 {
      "name": "cordova-android",
      "version": ">=4.0.0"
    }
```


If I tried to run the app I am getting following error. 

```
BlinkID after_prepare hook:
Failed to append largeHeap to AndroidManifest.xml application node
(node:16320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Operation failed
```

Please help me to fix this issue.

**Comment by matvidako** [comment]
Hi, 

in that case, use the branch with support for older version: https://github.com/BlinkID/blinkid-phonegap/tree/support/old-android-plugin
It now has support for IKad.

**Comment by jcular** [comment]
Closed due to inactivity.
