### ISSUE TITLE
Screen Oreintation

### ISSUE THREAD

**Issue by kashif-imagyn** [BlinkID/blinkid-phonegap#53]
In Iphone Screen is not auto rotating, and i want to customize the message below overlay.
Thanks

**Comment by jcular** [comment]
Hi @kashif-imagyn,

Currently on iOS autorotation is turned off by default, if you want to turn it on you can add custom code to the native iOS implementation of the plugin, add these two lines to `CDVMicroblinkScanner.m` in `scanWithCamera:command` method:
```
self.scanningViewController.autorotate = YES;
self.scanningViewController.supportedOrientations = UIInterfaceOrientationMaskAllButUpsideDown
```

To customise the message you will need to also change the native code, depending on what overlay you are using you'll need to find it's settings and in the settings property you can set the message property.
For example if you are using DocumentOverlay for iOS you'll need to find `MBDocumentOverlaySettingsSerialization.h` and add `sett.tooltipText = @"Your custom text";` below the line: `MBDocumentOverlaySettings *sett = [[MBDocumentOverlaySettings alloc] init];`

Kind regards,
Jure

**Comment by i1E** [comment]
Hi @diestel-r,

it is not possible for `DocumentVerificationOverlaySettings`, `DocumentVerificationActivity` does not support landscape orientation. It is designed for scanning in portrait only.

**Comment by diestel-r** [comment]
@i1E Alright, thanks for the info.
