### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by idistech** [BlinkID/blinkid-phonegap#6]
Hi, 
Ive been trying to get this plugin working within our Angular2/Ionic 2 application, but been having some problems.

The plugin doesnt like the registration key, and returns 'License Key Error'.

I have now simplified the problem, down to a license key issue...

a) We can build and deploy the demo as provided 'BlinkIdDemo', and it runs with no problems.
b) Change the Demo Package Id to one of ours, and use the generated keys from the portal, we get 'Un Licensed'/Key Failure..

I think it seems the Phonegap/cordova version is not reading the package name or license key correctly, and in some way 'hard coded' ?

Has anybody else had success in deploying this and reeplacing the license key ?

Best

`E ScanCard.java:338@main: INVALID LICENCE KEY
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: com.microblink.recognition.InvalidLicenceKeyException: Failed to validate licence key. Reason: Either license key or android context is null!
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at com.microblink.view.recognition.RecognizerView.setLicenseKey(line:746)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at com.microblink.activity.BaseScanActivity.onCreate(line:333)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.app.Activity.performCreate(Activity.java:6876)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.os.Looper.loop(Looper.java:158)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at android.app.ActivityThread.main(ActivityThread.java:7224)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at java.lang.reflect.Method.invoke(Native Method)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
10-31 19:16:14.312 20974 20974 E ScanCard.java:338@main: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by DoDoENT** [comment]
Hi!

Since this works with our demo app, can you please create a minimal example project which demonstrates the issue and send us the zip? We would be glad to investigate if there is a bug in cordova android wrapper.

**Comment by idistech** [comment]
Download the source from this git repo, follow the instructions
i) Build and install and confirm it runs.
ii) goto the blinkid developer portal and create a demo license for Android & IOS for your own package name
iii) Update the package id, the Android and IOS Keys, 
iv) Rebuild and re-deploy.

**Comment by i1E** [comment]
Hi @idistech,

we had an error in the [code sample](https://github.com/BlinkID/blinkid-phonegap#usage), there was missing argument in cordova.plugins.blinkIdScanner.scan() function: **imageType** - type of the image that will be returned in scan result. We have updated the documentation and if you update your code everything should work fine. The error was only in the documentation, the code in the [demo application](https://github.com/BlinkID/blinkid-phonegap/blob/master/www/js/index.js#L199) is correct.

Please let us know if this has solved your issue and sorry for the inconvenience.

**Comment by nusrathms** [comment]
Hi idistech,  I tried with source code from git but it is in ionic 1 version of app.

In your initial posted on 5thNov you said that you are developing ionic 2 app, can you please help me with any pointer/idea of how to integrate/make blinkId working with ionic 2 ?

I tried to modify the source code compatible with ionic 2 but no luck.

any help is much appreciated.

Thanks in advance.

**Comment by culoi** [comment]
@nusrathms For Ionic V2 follow https://github.com/BlinkID/blinkid-phonegap#ionic
Please note that GIT LFS  is required because file in iOS submodule exceeds GitHubs limited file size of 100MB.

**Comment by jcular** [comment]
Closed due to inactivity.
If any issues persist in newer versions please open another issue.
