### ISSUE TITLE
breaking backward compatibility

### ISSUE THREAD

**Issue by greggreenhaw** [BlinkID/blinkid-phonegap#62]
Not sure why you keep changing the scan method in the js. Like in the latest version the scan method requires and array of image types instead of one. This breaks previous versions. It would be better to add a new method with the newest functionality. As a hack to sense the new code I'm running
cordova.plugins.blinkIdScanner.scan.toString().indexOf('imageTypes') > -1 

You should have at least added a check to the js to fix the compatibility

 BlinkIdScanner.prototype.scan = function (successCallback, errorCallback, types, imageTypes, licenseiOs, licenseAndroid, language) {
        if (errorCallback == null) {
            errorCallback = function () {
            };
        }

        if (typeof errorCallback != "function") {
            console.log("BlinkIdScanner.scan failure: failure parameter not a function");
            return;
        }

        if (typeof successCallback != "function") {
            console.log("BlinkIdScanner.scan failure: success callback parameter must be a function");
            return;
        }

        if(type imageTypes == 'string') {
            if(imageTypes == 'IMAGE_CROPPED')
                imageTypes = 'IMAGE_DOCUMENT';
            imageTypes = [imageTypes];
        }

        exec(successCallback, errorCallback, 'BlinkIdScanner', 'scan', [types, imageTypes, licenseiOs, licenseAndroid, language]);
    };

**Comment by jcular** [comment]
Hi @greggreenhaw,

this is because we've added the ability to retrieve more types of images while scanning.
Sorry if this caused inconvenience but we don't believe that fix would make it clear what imageTypes is really used for and might cause more problems to other users.

Kind regards,
Jure
