### ISSUE TITLE
PhoneGap Build: Failed to install 'com.microblink.BlinkIdScanner'

### ISSUE THREAD

**Issue by calitidexvii** [BlinkID/blinkid-phonegap#69]
During build using PhoneGap Build, plugin fails to install. This may be related to issue #60, but since this is downloading from NPM by PhoneGap, I don't have the freedom to change the case.  

[Gist for Error in PhoneGap Build Log](https://gist.github.com/calitidexvii/c941c6264225c2d4f62b4e6ea5340e66#file-phonegap-build-blinkid-plugin-failed-txt)

**Comment by juraskrlec** [comment]
Hi @calitidexvii 

what PhoneGap (Cordova and Ionic) are you using for your project?

**Comment by calitidexvii** [comment]
PhoneGap CLI: cli-6.5.0, PhoneGap iOS: 4.3.1

**Comment by jcular** [comment]
Hi @calitidexvii,

is this issue still relevant to you, because in the newer versions script has been fixed?

Kind regards,
Jure

**Comment by calitidexvii** [comment]
Yes, thank you, @jcular!
