### ISSUE TITLE
In 4.2 version build failed issue :app:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by jassiwaliaVC** [BlinkID/blinkid-phonegap#76]
on doing ionic cordova build android i get this issue

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_cdbk63550k3sysl4sp6slfpfp.run(D:\WorkingFolderMvc\ID Scanning\platforms\android\app\build.gradle:145)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:createDebugCompatibleScreenManifests UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:javaPreCompileDebug UP-TO-DATE
D:\WorkingFolderMvc\ID Scanning\platforms\android\app\src\main\java\com\phonegap\plugins\microblink\overlays\serialization\BarcodeOverlaySettingsSerialization.java:3: error: package com.microblink.blinkid does not exist
import com.microblink.blinkid.R;
                             ^
D:\WorkingFolderMvc\ID Scanning\platforms\android\app\src\main\java\com\phonegap\plugins\microblink\overlays\serialization\DocumentOverlaySettingsSerialization.java:3: error: package com.microblink.blinkid does not exist
import com.microblink.blinkid.R;
                             ^
D:\WorkingFolderMvc\ID Scanning\platforms\android\app\src\main\java\com\phonegap\plugins\microblink\overlays\serialization\BarcodeOverlaySettingsSerialization.java:16: error: package R does not exist
        uiSettings.setSplashScreenLayoutResourceID(R.layout.mb_layout_splash_screen);
                                                    ^
D:\WorkingFolderMvc\ID Scanning\platforms\android\app\src\main\java\com\phonegap\plugins\microblink\overlays\serialization\DocumentOverlaySettingsSerialization.java:16: error: package R does not exist
        uiSettings.setSplashScreenLayoutResourceID(R.layout.mb_layout_splash_screen);
                                                    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors
:app:compileDebugJavaWithJavac FAILED

27 actionable tasks: 1 executed, 26 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
(node:12572) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
D:\WorkingFolderMvc\ID Scanning\platforms\android\app\src\main\java\com\phonegap\plugins\microblink\overlays\serialization\BarcodeOverlaySettingsSerialization.java:3: error: package com.microblink.blinkid does not exist
import com.microblink.blinkid.R;
                             ^
D:\WorkingFolderMvc\ID Scanning\platforms\android\app\src\main\java\com\phonegap\plugins\microblink\overlays\serialization\DocumentOverlaySettingsSerialization.java:3: error: package com.microblink.blinkid does not exist
import com.microblink.blinkid.R;
                             ^
D:\WorkingFolderMvc\ID Scanning\platforms\android\app\src\main\java\com\phonegap\plugins\microblink\overlays\serialization\BarcodeOverlaySettingsSerialization.java:16: error: package R does not exist
        uiSettings.setSplashScreenLayoutResourceID(R.layout.mb_layout_splash_screen);
                                                    ^
D:\WorkingFolderMvc\ID Scanning\platforms\android\app\src\main\java\com\phonegap\plugins\microblink\overlays\serialization\DocumentOverlaySettingsSerialization.java:16: error: package R does not exist
        uiSettings.setSplashScreenLayoutResourceID(R.layout.mb_layout_splash_screen);
                                                    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
    at ChildProcess.whenDone (D:\WorkingFolderMvc\ID Scanning\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by i1E** [comment]
Hi @jassiwaliaVC, 

thank you for the report. We will fix that issue, and release a new version of the plugin today.

**Comment by i1E** [comment]
Hi @jassiwaliaVC,

new version of the plugin is released. Please check the v4.2.1 and give us a feedback.

**Comment by jassiwaliaVC** [comment]
version 4.2.1 solvced my issue
