### ISSUE TITLE
URGENT Customize overlay

### ISSUE THREAD

**Issue by jassiwalia001** [BlinkID/blinkid-phonegap#79]
Hi I need to change overlay for blinkid how can i achieve it. Is there any code or which file to edit. As i am working on ongoing project so please allow me some fast response thanks.

**Comment by culoi** [comment]
Hello @jassiwalia001 

Unfortunately, there is no option for Customizing UI in the PhoneGap.

The solution is to use native SDK and create your own Custom UI overlay: 

https://github.com/BlinkID/blinkid-android#recognizerRunnerView

Best regards

**Comment by jassiwalia001** [comment]
okays
