### ISSUE TITLE
 build error for Android and iOS

### ISSUE THREAD

**Issue by guerson** [BlinkID/blinkid-phonegap#8]
Before I start I would like to congratulate you for your great work.

This code below is your own sample for building android and ios

```
# pull the plugin and sample application from Github
git clone git@github.com:BlinkID/blinkid-phonegap.git

# initialize and update submodules
git submodule init
git submodule update

...
```
$ git clone git@github.com:BlinkID/blinkid-phonegap.git
Cloning into 'blinkid-phonegap'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

Then I did it in my own way through HTTPS
and it works great with ANDROID

```
git clone https://github.com/BlinkID/blinkid-phonegap.git
git submodule init
git submodule update
cordova plugin add ../plugins_downloaded/blinkid-phonegap/BlinkID
ionic platform rm android
ionic platform add android
ionic build android
```

Than, i tried to build it for iOS before using XCODE for publishing. 
I had the same problem as ANDROID.
I had to clone the repo through HTTPS
```
git clone https://github.com/BlinkID/blinkid-phonegap.git
cd ./plugins_downloaded/blinkid-phonegap/BlinkID/src/ios 
git submodule init
git submodule update
git clone https://github.com/BlinkID/blinkid-ios.git       ------> the submodule too
cordova plugin add ./plugins_downloaded/blinkid-phonegap/BlinkID/
```

Now, for iOS I can scan but i dont see the result.
The Camera close after scanning with nothing in the callback.

```

    function scanBlinkId() {
...
        //scanButton.addEventListener('click', function() {    
        cordova.plugins.blinkIdScanner.scan(

            // Register the callback handler
            function callback(scanningResult) {
```


The only log i see in Xcode is 
```
THREAD WARNING: ['BlinkIdScanner'] took '10.166748' ms. Plugin should use a background thread.
[W] -[PPCameraManager updateCameraSession] [PPCameraManager.mm:244] 201 Should not have been observing autofocus
```

Please Help

**Comment by jcular** [comment]
Closed due to inactivity if problem persists in newer versions please open a new issue.
