### ISSUE TITLE
Code signing "MicroBlink.framework" failed. on xcode Version 10.0

### ISSUE THREAD

**Issue by shernir** [BlinkID/blinkid-phonegap#81]
I am getting **Code signing "MicroBlink.framework" failed** when i am trying to archive the project as Ad Hoc build on xcode 10, but it is working fine in old xcode versions and on device, even i tried the demo application on the documentation and i am getting the same error, and the below what i got from the build log

Failed to verify bitcode in MicroBlink.framework/MicroBlink:
error: Cannot extract bundle from /var/folders/jz/xmt34n614j36c71fthc0mrgw0000gp/T/IDEDistributionOptionThinning.bqx/Payload/E-Activation.app/Frameworks/MicroBlink.framework/MicroBlink (i386)

**Comment by culoi** [comment]
Hi @shernir ,

Could you please let us know if you have Code Sign On Copy in your Build Phases/Embed Frameworks checked.
Like in the screenshot below:
![Image](https://p14.zdusercontent.com/attachment/602488/wkApErwJ24m4AnSSmi3NcloDN?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..Bl6gyNQc2ytII4ic9llIQA.5ujuF_VC0vfrLnKp3tBcAaQRTImPpeXLakEnOW_Lm2w8ULhD04kiv2yfUun2zSBLT3g7hLbElNAf5FsU4_igA72ip2U1t9pKibh5qEowiOccyXUcyYR8kz8nOisDZa5kYsf50HHHiT3cztL5E0bp2QEj_VSuaK9OFX9c3n5D_f1bdGYBLzLKzeiBFSaTi--TQle8kpzm1BinpOLzVdvkJQIsyzTgPsLlGUVYq9T0Rs0or904z7hPpxxXqbBdjAHVXcIs_2dQbALp_qbomdkIuC6kKqfxVZBoWSmMARhpBa4.oM5yt5NimXoEqKP5xv4L5A)

Regards

**Comment by shernir** [comment]
Hi Thank you for your prompt reply please find the below 
<img width="662" alt="screen shot 2018-09-19 at 11 58 04 am" src="https://user-images.githubusercontent.com/29011400/45742859-937a7500-bc03-11e8-9e12-bc9afad404d9.png">

**Comment by jcular** [comment]
Hi @shernir,

we are unable to reproduce this issue, could it be possible for you to send us a minimal project that reproduces this issue?

Kind regards,
Jure

**Comment by jcular** [comment]
Hi @shernir,
 I think we found the issue, in build settings try disabling the bitcode, set Enable Bitcode setting to No
Kind regards,
Jure

**Comment by shernir** [comment]
Dear @jcular 

i disabled it already but nothing changed please note i am facing this issue when i try to archive Ad Hoc build with xcode 10, please find the requested project thank you

https://drive.google.com/file/d/1DTRa_PdKAvXduOpLnOzyjb1el513Qb9j/view?usp=sharing

**Comment by jcular** [comment]
Hi @shernir,

I'll try to check out your project as soon as I can, but could you try to follow the instructions [here](
https://github.com/BlinkID/blinkid-ios#-unsupported-architectures-when-submitting-app-to-app-store) to add that script in your build phases and then trying to archive it?

Kind regards,
Jure

**Comment by jcular** [comment]
Hi @shernir,

I tried your project and I tried to archive it for Ad Hoc, I get a different error but adding the run script fixed the issue. Let us know if that worked for you.

Kind regards,
Jure

**Comment by jcular** [comment]
Hi @shernir,

I don't think this is related to us, unzip your ipa file, open the payload and inside it you'll find a file named as your app, right click it and show package contents, inside check if embedded.mobileprovision is inside, if it's not something probably went wrong with xcode.
Check your profiles and certificates in preferences inside xcode.

Kind regards,
Jure

**Comment by shernir** [comment]
Hi @jcular 
Yes you are right it was profiles issue so the run script solved the issue thank you very much for you support 

Regards,

**Comment by ManigandanRaamanathan** [comment]
@shernir how do you run the code?
