### ISSUE TITLE
Failed to install 'blinkid-cordova': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh! The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by HannahCarney** [BlinkID/blinkid-phonegap#88]
Works fine on iOS - cannot get this to work on android. 

When adding the plugin:

> [Error during processing of action! Attempting to revert...
> Failed to install 'blinkid-cordova': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
> The "path" argument must be of type string. Received type undefined
>     at assertPath (path.js:39:11)
>     at Object.resolve (path.js:1090:7)]

**Comment by HannahCarney** [comment]
Further inspection it appears the plugin doesn't support version 7.1.2 of cordova-android. To fix change cordova platform add android@7 to cordova platform add android@7.0.0

**Comment by i1E** [comment]
Hi @HannahCarney, we just released the new version of the plugin (v4.4.0), it should work with cordova-android v7.1.2.

**Comment by HannahCarney** [comment]
Thanks guys - will give it a go!

**Comment by i1E** [comment]
HI @HannahCarney, does the new version of the plugin work for you? If everything is OK, please close the issue.

**Comment by HannahCarney** [comment]
It works yes thank you for the update!
