### ISSUE TITLE
blinkid-cordova fails to install

### ISSUE THREAD

**Issue by AlibekJ** [BlinkID/blinkid-phonegap#91]
A typo in initIOSFramework.sh line 4, which should be

```
LINK='https://github.com/BlinkID/blinkid-ios/releases/download/v4.4.0/blinkid-ios_v4.4.0.zip'
```

**Comment by jcular** [comment]
Hi @AlibekJ,

Thx for reporting this, I fixed the typo in the script and published a new version on npm, v4.4.1.

Kind regards,
Jure
